### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lrq3000** [jherkenhoff/libqalculate-android#6]
Can you please clarify the license? Currently libqalculate-android is not open-source due to a lack of license.

I suggest to use the same license as libqalculate to simplify things: GNU General Public License v2.0

https://github.com/Qalculate/libqalculate/blob/master/COPYING

**Comment by jherkenhoff** [comment]
Added in [3c22531](https://github.com/jherkenhoff/libqalculate-android/commit/3c22531d8d5344252e53d5fd2ae20bf86d278607)

**Comment by lrq3000** [comment]
Awesome, thank you so much! :D
